import { useRef, useState } from 'react';
import { ArrowRight, X } from 'lucide-react';

export default function DemoTour({ language, onNavigate }: { language: 'en' | 'fr'; onNavigate: (page: string) => void }) {
 const [step,setStep]=useState<number|null>(null);const trigger=useRef<HTMLButtonElement>(null);const fr=language==='fr';
 const pages=['Appointments','Agenda','Activity Log'];
 const steps=fr ? [['Consultez les demandes','Explorez les filtres et les statuts pour repérer les rendez-vous à traiter.'],['Explorez le planning','Passez entre les vues mensuelle, hebdomadaire et quotidienne.'],['Suivez l’activité de l’équipe','Consultez les confirmations et les indicateurs de prise en charge.']] : [['Review incoming requests','Explore filters and statuses to find appointments that need attention.'],['Explore the schedule','Switch between month, week and day views.'],['See team activity','Review confirmations and appointment-handling metrics.']];
 const close=()=>{setStep(null);requestAnimationFrame(()=>trigger.current?.focus());};
 const start=()=>{setStep(0);onNavigate(pages[0]);};
 return <div onKeyDown={event=>{if(event.key==="Escape" && step!==null){event.preventDefault();close();}}} className="rounded-2xl border border-white/20 bg-black/15 p-4 text-white">
  {step===null ? <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-white/85">{fr?'Découvrez le parcours en trois étapes.':'Explore the workflow in three steps.'}</p><button ref={trigger} type="button" onClick={start} className="rounded-full border border-white/25 bg-white/10 px-4 py-2 text-sm font-semibold hover:bg-white/20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200">{fr?'Visite guidée':'Take a quick tour'}<ArrowRight size={14} className="ml-2 inline"/></button></div> : <div className="flex items-start gap-3"><div aria-live="polite" className="min-w-0 flex-1"><p className="text-xs font-semibold text-white/70">{fr?'VISITE GUIDÉE':'QUICK TOUR'} · {step+1}/3</p><h2 className="mt-2 text-base font-semibold">{steps[step][0]}</h2><p className="mt-1 text-sm leading-relaxed text-white/85">{steps[step][1]}</p><button type="button" onClick={()=>{if(step===2){close();return;}setStep(step+1);onNavigate(pages[step+1]);}} className="mt-3 rounded-full bg-white px-4 py-2 text-sm font-semibold text-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-200">{step===2?(fr?'Terminer':'Finish'):(fr?'Étape suivante':'Next step')}</button></div><button type="button" onClick={close} aria-label={fr?'Fermer la visite':'Close tour'} className="rounded-full p-2 hover:bg-white/15 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200"><X size={18}/></button></div>}
 </div>;
}
