import { useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';

export function PrivacyLink({ language }: { language: 'en' | 'fr' }) {
 return <button type="button" onClick={()=>document.dispatchEvent(new Event('clinahir:privacy'))} className="rounded underline underline-offset-4 hover:opacity-80 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--brand-primary)]">{language==='fr'?'Utilisation de vos informations':'How we use your details'}</button>;
}
export default function PrivacyNotice({ language }: { language: 'en' | 'fr' }) {
 const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const fr=language==='fr';
 useEffect(()=>{const show=()=>setOpen(true);document.addEventListener('clinahir:privacy',show);return ()=>document.removeEventListener('clinahir:privacy',show);},[]);
 useEffect(()=>{if(!open || !dialog.current)return;const node=dialog.current;const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;node.showModal();document.body.style.overflow='hidden';return ()=>{node.close();document.body.style.overflow=overflow;previous?.focus();};},[open]);
 return <dialog ref={dialog} onCancel={event=>{event.preventDefault();setOpen(false);}} aria-labelledby="privacy-title" className="w-[calc(100%-2rem)] max-w-xl rounded-[28px] border border-[var(--border)] bg-white p-7 text-[var(--text-primary)] shadow-2xl backdrop:bg-black/50"><div className="flex items-start justify-between gap-5"><h2 id="privacy-title" className="text-2xl font-semibold">{fr?'Utilisation de vos informations':'How we use your details'}</h2><button autoFocus type="button" aria-label={fr?'Fermer':'Close'} onClick={()=>setOpen(false)} className="rounded-full p-2 hover:bg-[var(--surface-muted)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--brand-primary)]"><X size={20}/></button></div><div className="mt-5 space-y-4 text-sm leading-relaxed text-[var(--text-body)]"><p>{fr?'Clinahir utilise les informations envoyées dans ce formulaire pour comprendre les besoins de votre centre, vous contacter et préparer une démonstration ou une proposition.':'Clinahir uses the details submitted in this form to understand your center’s needs, contact you, and prepare a demo or proposal.'}</p><p>{fr?'Votre demande est enregistrée dans notre service de stockage et transmise à notre outil interne de suivi des prospects. Les paramètres de campagne peuvent être associés à la demande pour identifier son origine.':'Your request is saved in our storage service and forwarded to our internal lead-management tool. Campaign parameters may be attached to identify where the request originated.'}</p><p>{fr?'Nous comptabilisons les visites et les clics sur les boutons de démonstration sans inclure le contenu du formulaire dans ces événements. Ce suivi respecte les préférences de confidentialité du navigateur lorsqu’elles sont disponibles.':'We count page visits and demo-button clicks without including form contents in those events. This tracking respects browser privacy preferences where available.'}</p><p>{fr?'N’envoyez aucune information médicale ni aucun dossier patient. Pour toute question concernant vos informations, utilisez le formulaire de contact.':'Do not submit medical information or patient records. For questions about your details, use the contact form.'}</p></div><button type="button" onClick={()=>setOpen(false)} className="mt-6 rounded-full bg-[var(--brand-primary-hover)] px-5 py-3 font-semibold text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--brand-primary)]">{fr?'Fermer':'Close'}</button></dialog>;
}
